apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  destination:
    namespace: webapp
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: helm/webapp
    repoURL: "https://github.com/sharet-adl/argocd-course-webapp-config.git"
    targetRevision: test-follow
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
